CREATE DATABASE IF NOT EXISTS file_service_db CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS version_service_db CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS activity_service_db CHARACTER SET utf8mb4;
